# 記得改 properties 為 UTF-8
# port config (預設就是 8080 ，若需修改可以從這邊)
server.port=8080

# Base Url
server.servlet.context-path=/mall

# jsp config
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# for http put and delete method
spring.mvc.hiddenmethod.filter.enabled=true

####################### Datasourse Config ##################
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Mall;trustServerCertificate=true;serverTimezone=Asia/Taipei
spring.datasource.username=sa
spring.datasource.password=as

#################### Hibernate (JPA) Config #######################
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# if you want to use "update" model, change this
##spring.jpa.hibernate.ddl-auto=none

## 不強制命名轉換
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


## 圖片大小上限調整
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

## 時間顯示調整
#spring.jackson.time-zone=GMT+8
#spring.jackson.date-format=yyyy-MM-dd HH:mm:ss